<?php

namespace Dpp\Cbe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRubriqueRepository extends EntityRepository
{
}
