<?php

namespace Dpp\Cbe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    function findRubFrom( $menuName) {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT r.pathurl, r.libelle, mr.position FROM DppCbeMainBundle:Menu m, DppCbeMainBundle:MenuRubrique mr, DppCbeMainBundle:Rubrique r  WHERE m.libelle = :menuName and mr.menuId = m.id and mr.rubriqueId = r.id"
            )
            ->setParameter( 'menuName', $menuName)
            ->getResult();
    }
}
