<?php

namespace Dpp\Cbe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    function findAvailableNews() {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT n.titre, n.description, n.mediafile FROM DppCbeMainBundle:News n WHERE n.dateDebut <= CURRENT_DATE() and n.dateFin >= CURRENT_DATE()"
            )
            ->getResult();
    }
}
